[project]
name = "training-sample-code"
version = "0.1.0"
description = ""
authors = [{ name = "samzong.lu", email = "samzong.lu@gmail.com" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.2",
    "swanlab>=0.6.8",
]
